"""Fixtures for the geometric-equivalence suites.

Each `test_NN_*.py` is generated by cad-fingerprint from the matching reference
in `ref/stl/` — Luca Jost's part, moved into the frame the parametric part is
built in — and is satisfied by the violin preset of that part.

Regenerate the references with `python tools/make_locals.py`.
"""

import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "src"))

from gams import (  # noqa: E402
    VIOLIN, Rig, base, clip, grip, hammer, handheld_hammer, handle, holder,
    knob, mic_arm, slider, top,
)

RIG = Rig(VIOLIN)

PARTS = {
    "test_01_base": base,
    "test_02_top": top,
    "test_03_slider": slider,
    "test_04_holder": holder,
    "test_05_mic_arm": mic_arm,
    "test_06_clip": clip,
    "test_07_hammer": hammer,
    "test_08_knob": knob,
    "test_09_handle": handle,
    "test_10_grip": grip,
    "test_11_handheld": handheld_hammer,
}


@pytest.fixture
def part_under_test(request):
    """The part this module fingerprints, built at the violin preset."""
    return PARTS[request.module.__name__.rsplit(".", 1)[-1]](RIG)
