"""Fixtures for the geometric-equivalence suites.

Each `test_NN_*.py` is generated by cad-fingerprint from the matching upstream
reference in `ref/stl/`, and is satisfied by the violin preset of the
corresponding parametric part.  References captured in assembly coordinates are
translated to the part's own frame first (see `ref/stl/*_local.stl`).
"""

import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "src"))

from gams import VIOLIN, Rig, base, top  # noqa: E402

RIG = Rig(VIOLIN)
PARTS = {"test_01_base": base, "test_02_top": top}


@pytest.fixture
def part_under_test(request):
    """The part this test module fingerprints, built at the violin preset."""
    return PARTS[request.module.__name__.rsplit(".", 1)[-1]](RIG)
