"""Auto-generated geometric fingerprint tests for Holder.

Generated by cad-fingerprint from: ref/stl/04_holder.stl
Reference volume: 4500.2078 mm³
Reference surface area: 4672.2566 mm²
Reference bounding box: (52.5000, 48.6250, 18.0000) mm

To use these tests, create a conftest.py with a fixture::

    @pytest.fixture
    def part_under_test():
        # Return the Part to validate.
        return my_build_function()

Any procedural implementation that passes all tests is
geometrically equivalent to the reference STL mesh.

Note: Face inventory tests are omitted (STL has no analytical
surface types). Cross-section and radial profile tests are fully
functional.
"""

import math
import base64
import bisect
import struct
import zlib

import pytest

from build123d import Part
from OCP.BRepAdaptor import BRepAdaptor_Curve, BRepAdaptor_Surface
from OCP.BRepAlgoAPI import BRepAlgoAPI_Section
from OCP.BRep import BRep_Tool
from OCP.BRepMesh import BRepMesh_IncrementalMesh
from OCP.BRepTools import BRepTools
from OCP.TopLoc import TopLoc_Location
from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeFace
from OCP.BRepGProp import BRepGProp
from OCP.GCPnts import GCPnts_AbscissaPoint
from OCP.GeomAbs import (
    GeomAbs_BSplineCurve, GeomAbs_BSplineSurface, GeomAbs_Circle,
    GeomAbs_Cone, GeomAbs_Cylinder, GeomAbs_Ellipse,
    GeomAbs_Line, GeomAbs_Plane, GeomAbs_Sphere, GeomAbs_Torus,
)
from OCP.GProp import GProp_GProps
from OCP.IntCurvesFace import IntCurvesFace_ShapeIntersector
from OCP.ShapeAnalysis import ShapeAnalysis_FreeBounds
from OCP.TopAbs import TopAbs_EDGE, TopAbs_FACE, TopAbs_REVERSED, TopAbs_VERTEX
from OCP.TopExp import TopExp_Explorer
from OCP.TopTools import TopTools_HSequenceOfShape
from OCP.TopoDS import TopoDS
from OCP.gp import gp_Dir, gp_Lin, gp_Pln, gp_Pnt


# ═══════════════════════════════════════════════════════════
# Reference fingerprint data
# ═══════════════════════════════════════════════════════════

REF_VOLUME = 4500.2078
REF_SURFACE_AREA = 4672.2566
REF_CENTER_OF_MASS = (-0.0000, 19.6455, 3.5986)
REF_BBOX_MIN = (-26.2500, -3.0000, -0.0000)
REF_BBOX_MAX = (26.2500, 45.6250, 18.0000)
REF_BBOX_SIZE = (52.5000, 48.6250, 18.0000)

REF_INERTIA = {
    "Ixx": 915116.0130,
    "Iyy": 1157774.2355,
    "Izz": 1918479.8531,
    "Ixy": -0.5664,
    "Ixz": 0.0484,
    "Iyz": 120180.3767,
}

REF_EDGE_INVENTORY = [
]

REF_CROSS_SECTIONS = [
    {"position": 0.1800, "area": 1062.0545, "centroid_x": -0.0000, "centroid_y": 22.5584},
    {"position": 0.9470, "area": 1062.0546, "centroid_x": -0.0000, "centroid_y": 22.5587},
    {"position": 1.7139, "area": 1062.0549, "centroid_x": -0.0000, "centroid_y": 22.5588},
    {"position": 2.4809, "area": 1062.0555, "centroid_x": -0.0000, "centroid_y": 22.5587},
    {"position": 3.2478, "area": 200.4577, "centroid_x": -0.0000, "centroid_y": 24.9392},
    {"position": 4.0148, "area": 172.7784, "centroid_x": -0.0000, "centroid_y": 23.6787},
    {"position": 4.7817, "area": 164.0774, "centroid_x": -0.0000, "centroid_y": 23.1606},
    {"position": 5.5487, "area": 163.6398, "centroid_x": -0.0000, "centroid_y": 23.1319},
    {"position": 6.3157, "area": 163.6352, "centroid_x": -0.0002, "centroid_y": 23.1316},
    {"position": 7.0826, "area": 60.0341, "centroid_x": -0.0000, "centroid_y": 2.2390},
    {"position": 7.8496, "area": 60.0235, "centroid_x": -0.0000, "centroid_y": 2.2389},
    {"position": 8.6165, "area": 60.0079, "centroid_x": -0.0000, "centroid_y": 2.2387},
    {"position": 9.3835, "area": 59.9982, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 10.1504, "area": 59.9981, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 10.9174, "area": 59.9981, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 11.6843, "area": 59.9981, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 12.4513, "area": 59.9981, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 13.2183, "area": 59.9980, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 13.9852, "area": 59.9980, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 14.7522, "area": 59.9980, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 15.5191, "area": 59.9980, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 16.2861, "area": 59.9980, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 17.0530, "area": 59.9980, "centroid_x": -0.0000, "centroid_y": 2.2385},
    {"position": 17.8200, "area": 59.9980, "centroid_x": -0.0000, "centroid_y": 2.2385},
]

REF_RADIAL_PROFILE = [
    {"position": 0.1800, "radii": {0.0: 21.9267, 30.0: 19.2442, 60.0: 20.2077, 90.0: 24.3123, 120.0: 20.2077, 150.0: 19.2442, 180.0: 21.9267, 210.0: 29.8806, 240.0: None, 270.0: None, 300.0: None, 330.0: 29.8806}},
    {"position": 1.4400, "radii": {0.0: 21.9266, 30.0: 19.2446, 60.0: 20.2082, 90.0: 24.3109, 120.0: 20.2082, 150.0: 19.2446, 180.0: 21.9266, 210.0: 29.8805, 240.0: None, 270.0: None, 300.0: None, 330.0: 29.8805}},
    {"position": 2.7000, "radii": {0.0: 21.9263, 30.0: 19.2450, 60.0: 20.2079, 90.0: 24.3094, 120.0: 20.2079, 150.0: 19.2450, 180.0: 21.9263, 210.0: 29.8804, 240.0: None, 270.0: None, 300.0: None, 330.0: 29.8804}},
    {"position": 3.9600, "radii": {0.0: None, 30.0: 7.6131, 60.0: 13.1918, 90.0: None, 120.0: 13.1918, 150.0: 7.6131, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 5.2200, "radii": {0.0: None, 30.0: 7.2746, 60.0: 12.6000, 90.0: None, 120.0: 12.6000, 150.0: 7.2746, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 6.4800, "radii": {0.0: None, 30.0: 7.2746, 60.0: 12.6000, 90.0: None, 120.0: 12.6000, 150.0: 7.2746, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 7.7400, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 9.0000, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 10.2600, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 11.5200, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 12.7800, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 14.0400, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 15.3000, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 16.5600, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 17.8200, "radii": {0.0: None, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
]

# Reference surface mesh — the triangulated reference surface, used by
# the Hausdorff distance tests. Vertices are 16-bit quantised over the
# bounding box (sub-micron), zlib-compressed and base64-encoded.
REF_MESH = {
    "encoding": "q16",
    "vertex_count": 1350,
    "triangle_count": 2696,
    "bbox_min": (-26.250000, -3.000000, 0.000000),
    "bbox_max": (26.250000, 45.625000, 18.000000),
    "index_bits": 16,
    "max_triangles": 20000,
    "deflection": 0.073788,
    "angular_deflection": 0.35,
    "resolution": 0.003666,
    "candidate_resolution": 0.073788,
    "vertices": (
        "eNolmHl8jlf6xu8IQVC1K2lqi+VJYovEllhq0KYdozpHieVNus6UqmqpKvpUiaJq67Q10iRC"
        "LMc2xpAyqoioWEqTokVbxtaUqJ1EkvO7v/39c33O57znPec+133dy3Nih2XO2On9Z1hq2llv"
        "9nMD37c6zss56w0ddvPiPh0HF571vOFfX6oXeWZ4cOH0yKCk+ZeXRZYlBRfOjDqZNPzXkVF2"
        "RLOiEdG1RwYXFke/PfJs0aft64wKLtzSoeeoz36r1bFCxwWd7ozqe2VHp8zRv1z5IqZwdHBh"
        "ny69A+Ou7oidHwguvB33XeDW1Yhu7ZKDCy90H5L8SvH3PbJ1HJIwN3lpcd/4ncl5xf9NuJR8"
        "pbhPb6fzg/pUSwm9dqRPq5QW1wKPx6YEF27s1zWly7Xb/fql9Lo2p//AlMevhQ2MTcnL2div"
        "b8ovi+v3j01JTdvYr33K7sX1+tVOmb/4sb4uOTVtUJ9LyU8s7tk7W8chCf9OvrXotYRJyQsW"
        "5fRspzMXusckP7aoaY/fAtkLv+g2P5CadjsuPdBqYXzXwYGMBQ9iC0enpvXpsnH03I/3x1SM"
        "Sk0r6BQ8Onn+qU6DR0V8FNOxjs5s6fDZyDNzD7WvPTI1rTj61IgP56RHlyWlps2MChsR+eGa"
        "qNFJB1IvK6upadMjs4a/OOu5yKJhMvOONzClaHHYwNnPtb1ovTPD83KmK9t5OTOjao/MyymO"
        "rjMqL2dLhwrFgk6Fo/Ny+nSZH8jLuR3XLjkv50L3bMWQBKc4qA88JAbYLTGwdjXefGo13py8"
        "hp2fWo2Xn1qN31uuwoZRq7BheTZWBWdj5/mV2BmxEsuvr+AWf1vBja5lcbtNWdw0KIu7ly3n"
        "7s8sh42o5TCzKROWJmTCW0omvDXIhMkTGXB7OANu52TAdlIG/P85A/4fycAjkoF3rqfjqYPp"
        "+O67dHy3Kx1vHkzHs1+mw9LBdLy/Mx2/H0hHA6fTUYVkoJN76ejkkQyUk5SBovploKWJGehq"
        "QwZKO5GB6tpnosAJmahxdybKjFqOSgPLUWxQFhoOzULD+7JQ9bUsFP7hCtR+fQXKNyuJguBs"
        "4qJtNnFRkU2ktFxF1BxfRQR9mY4yG67GywdXE3eT1xBxLVfh5eBsvHx9BV6+loWXg7LwctRy"
        "vDwhEy+fyMDLSRl4WTLwMjwkBtg5MTBywZVS641cUHc1eKWUmbqrEwPbF2Tr+NcFMxS/XXgj"
        "OzGwacn8e4mB6MXbViYGpix5YUViYN6CA/rr3z9LvZ0Y2PxJ6fLEwHf/eDczMdBo2Ws3EgPn"
        "Pq+elhj4cdmMzxIDsuGLs9Ybt/nuaevt3Rpz0npl2/9aYL2mu0YcsV7wuhpTrRe+d+AB672+"
        "4atJ1quyv0mu9XZuCrxhvaP5x7+yXtHmm2OsN+3I219a7+6Wt1+2Xs3vgrdY7/zW4mSd/37y"
        "Buttyhk2wnrHTp7UuyRt32Z059Mtsqx3YUf1wdZr9POwNOvVOPfup9Z7eueQROulHC+Jtp5f"
        "WElxyVeL/2S9f31XFGm9L3cd7GW9m0c3eNb779el3ayX+O2Qdjp/+Ic21kvb3SrGer0P9W2t"
        "p+x5Uv97Ln9BK+tlHMhrobbt+ZuuefebC82sN2n/7+F6o70zm1tvUd7lMOt9u+9YE+vt35ve"
        "1HrR+9Y3VptzpzW0XunerQ2s99fcAfWVh9zQumpn7qHa1nvm5OH21vv5/EcL1eYfp3TQfS7N"
        "m2u9IaeDO6oGit6Zab3ATy/qeMmV56Zb741fMnR8rjhisvVmndui41rXLymH/zzPfMObS5XD"
        "9RdZX36r90vW23Pn1Gjl4d6rw/SU+9efsV630rFPWW/7ZfZ/7cE55WRXEefuuIIla4thbN7v"
        "MDbiBlw1vgVL75UNUsb23IalseVbu6qFd+Hq0D1Yiq1o1Ml67Upg6VTFm7p+TClcLXgAS0nu"
        "SEvrfVIGV++Uw9I21/JR6yVUwNXPFbBU7CYrSyMdXG1zsFTsYMk5WNo5P2qN9UI/ilirnppb"
        "rjjtw39b5iuXMV+umJ3afx2/Hi/n13kV1subuWUd84866/0yo3wdM/P+GB9XvOO3WA+W6jj0"
        "vf9HZppN49dm01jf413WJ73DDj3eZbcZb7Nz0juctXUiZ915k9NnvI09/SZgz4rxRNyK8URc"
        "vwlYfudNLN86EcuZTwywJjHQ+kVi59cXiabwV4im9q8SX5/+jYgbNIaImzWWSBw8ltgseI3Y"
        "7PQ60dpoPJE7YDxR/NZ44tQNIQYXDSIGExKJweABxOCFvsRg2V+JwXMJxODCIcRgaXdisN9g"
        "YrBjHDHYcBAxOKMzMVj9aWLwVntiMCyRGJwRSQwOfoIY7NCWGMweQAyWtSIGm/YnBn9tTgze"
        "DicGm4eh6o1t0VW6h6629CMq34tCXWMfJx7/0h6NDexLPNbqiNL+1Id43NoJpQ2MQWNbWqPP"
        "cY8QFxtaodszDYmLzBbofGx94uLjZug/vC5xMSWcuLhZm7h4KYz5olrExbNNWF+pJnExoDH7"
        "9AolOtKrER3NqxId31QhOhZXJi76NuRcPxjl96/PLYbW5RZvPYz9Kx/C8ss1sblXDaxdUom4"
        "2FAdm7tUIy4OBhEXJ0KIi4gg4uKTKsTF+MrERbYQF2OCiYvUSsTFk0Jc7A0iLpoHERd1hbhY"
        "IcTFk0Jc1BXiQoS4eKE3mWp3F87K7kWmCo/jrOSunFK9F5lqZjfOmtOdUxYmkKnG9eCsTj05"
        "pXsCmaqgJ2cNjueUKglkqnXxnHUunrNux3NWSaiIc79VXx3k3K5gxiXVXgh27mglpzPtqnWu"
        "4lxQpYcqOzel6sNVnTNBkSHOFYeUVXPusDyr+EHIjVDnXpKZigkh12o610J2KoaF/P6Qc5Xk"
        "nmJ4yM2HnasqMXWc6x9ys65zHeW1es4tDLlW37mpsqKBc1eloJFzLuR8Q+emB91/xLlFVQ83"
        "di6mUp0w/Ve1tU2cqx78aLhzTapP1Bmp3KiZc7VD2+tMwyoVzfXcGgWPOfdkyNGWzj1bc7TO"
        "/LPqnAjn0msdbeFclepeG7WndkQr5+aGbmyrpzw8Un9tXbOB5qOH6k5o7dwPtUZHOre53iu6"
        "8ovas6Kce7FBd135Vp150c6NqDeuvXMRjS7pzKAGUR2cu9F4XDvn/txov473NTmm42cf6dFR"
        "TwwL1T2Tm87W8RuPblScEh6uMx88xnhoM35d0pxfM1uyvkML/rs6gn2CW7Fndhv2PxrBWUvb"
        "ce6CNljyXiSWDI3GtsfbYWdYB2y+6GH/kY7cZVIU93q1M3e8Ec19r8Vw96Ed4CEpFk6Wd4Qf"
        "GwdX33WCt5+7wuHFzvB5uxvcnoqB59+6w/mmLvC/uwe+eCEWv0zsiY9ux+KvavH47oU4vDk5"
        "Hm/ui8e/G+Pw9dV4/H48Dg3ciEcPP8ShjYJ4dLItDs0siEc/4+PQUtt4dFU1Do2l90RvU2LR"
        "3s0e6PBQFzTZqgf6LI1Bq3Hd0W1oDBp+0Ilx5W/BO4eZyd/PuMphVp7O419dDrFDrTx2m3WQ"
        "nVP2ccr9fE48mcvpC/KxZHwuVj2Zj4XRuVjbJh/LH8rlFl4+N6qXy+2eyeemPXO5dVo+PMzO"
        "hYd7uTBT4yAszd0HY2kHYa93HkwOPgSrDfbDcMRh2K7xDcw3OYIXmh/AI+2/xTsmH0+NPorX"
        "sg/iwbXH8Gadw3j2oQK8/I8jeHxOId7vfBQlNDmOKs4fQyFfnUAtawtQzvgf0JL/PVp6+QTq"
        "6ngKpSX9gOrKTqPAYadQ47GfUGbgDCpd+wu6Hfszup16FiXPOoeqP/4f45Tz/JpxgV/XX2J9"
        "z4v899+/ss9Dl9lz82/sf+pXzlp5lXOX/YYl865hyfPXsW3QVexscxObbxRj/4+3uMv7v3Ov"
        "iXe4Y/l17lt6l7un3ISHl+7Dyfpb8LOtBK5+ug1vRaVweP0OfLoHcHvxLjzfLYPzHffg/3A5"
        "vhh3H7+8X4GPpAR/1XP47vUSvPmBw5tHHf7dUYKv7zv8fq4EDZQ79HC+BG385NDJ3hI080+H"
        "fqaWoKUYh67qlqAxW4HeZt1HexXl6PDEPTTZsRx9htxDq33L0G2Du2g45A7jGSZimkjTYa/N"
        "EClMypotsnbUvo9E0pMLFolsfuHQpyLnXt60TIR+Q6T6s4ffFtk0+PkJIpMGFY0VGf108isi"
        "LyceTBFZ+ETrkSJnBkwaKvJk/x2DRX7sdztRZN7jEf1Fkvv+ubfIc33GaWy90fvDGN2nV1q0"
        "SO1e69qILEnY1lykZ8LXTUWqJOxvIEI1Efn7mCZZIrvGZq4QiRpXI1vkX68PXyWS+MaHq0Xu"
        "Tvh8jciWt1LXirw36Rmr+08uUew2Zeo6keZTTyvWnl5/vYj4bRSvv8/45w+Y/2YWa9bMZr0/"
        "h/8+PY99qs9nz60fs/9fFnJW4SLO7bsEGz79BHv4uhEJXwozg9JgKSUDxoZmwV5UNkxeWA2r"
        "0ywM310Pb4M3wduczfC2fAu8Ld0Kb6/nwFvL7fC2bQe8td4Jb299BW8Zu+Btzdfw9vFueBu8"
        "B96u74G3sXvhbd9eeCvdC298L4iQo0TIWiJkLWtBY0BlWHOXMaAIucsYUITcZQwoQu4yBhQh"
        "dxkDqmc1dxkDipC7jAFFyF3GgCLkLmNAEXKXMaDaplnLGFDnNWvpvKLeSLOWMaAIWcsYUISs"
        "ZQyoCtSsZQyoqtOsZQyoitWsZQwoQtYyBlSeNWsZA+o+mrV0H0URspYxoAhZyxhQhHxlDChC"
        "vjIGFCFfGQPqWZqv9CxF5UozlXKlqN4/zzyoGr7IelDtucw+oAg5yhhQhBxlDKj6uYo9oAjZ"
        "yRhQhOxkDChCdjIG1LNucl9QhOxkDChCdjIGVG3cgTdQhOxkDChCdjIGFCE7GQOqRErwC6hq"
        "LMFfoK4vwY+g5oES/AuKkJeMAUXIS8aAIuQlY0AR8pIxoHJ1/w9d3UdX5CVjQBHykjGgCHnJ"
        "GFDn76Bbxtbyq7Wst5YdrGVPaznFWs61FkusxTZrsdZa7LeWG1nLHXVeb20tPFgLM9bClbWw"
        "Zy18WgvD1sK5tXjBWvxiLZ6yFt9Zizetxb/6L/W4WqUasBZVWItOrEU51qIla1GXtejNWhRo"
        "LZrUfQo4C91ai5KtRdu65gi2oX9riQhriRFriRod53MvIks/I/O5L9FnLfFoLRFqLTGrVh2E"
        "K+LaWiLdWvK/6lwrgvjh5SeU51/Kdyjz1AvxqSDiU1PEp8qIT90Rn0okPrVJfKqV+FQu8all"
        "4lPdxKfeiU8FFJ+aKD5VUnzqpvhUUvGpreJTbcWn/mpG1oosPjVafOq1+FRw8anp4lPlxafu"
        "i08PID5dgfj0CeLTM4hPFyE+fYX4dBri03uITx8iPp2J+PQq4tO9iE8/Iz4djvj0POLTBYlP"
        "XyQ+nZL49E7i002JT38lPh2X+HRf4tOP6d1zYYOeTXy6OPHp68Sn0xOf3k98ukHx6Q/Fv5oH"
        "2zMrrGq+psvWKJjkVlfX2HH/qqHR6nbWohqTt5vmMn4il/l/5LLG5bI+dR//jczDX0vXVz2n"
        "+6xZfFHklRWuSMSmD7omcnzpezdFij5ZeFeE9zpdszlwRqvz1mUnRVZu/2+ByIGvdh/RnLZn"
        "/QGRnXnTcrU658ftEkk4cvJLnT+WvEVkwPeFG0S+ONlR6+D3pyZrvbv60/o0jfqzh7XS7Th/"
        "aqFmzksn5modKdo9U2TylWXTteIUvzJZq8bvrbTGVb5ZOEak+Nakl0T+c6dmQCvjvc+HqYX3"
        "mwxRBZYueUotfxCs1W1K2dheWuXLj3YViamI0l77h4pZmkWHu1MttQq7qEd1HzdV85J9Y/kD"
        "EV4zNGe+maVaDpr4QbnInkl/qhCZP/l/is9PGe30LlNzFB+dXuyo+9p7yf/eZ7z3A+a/mMWa"
        "CbNZ32sO/62Yyz6bP2JP8zGn8NWsGUw4N1GwYZVgT5sgbDschJ2fVsLmWcHY/3ll7nK0Cvfy"
        "qnLHtdW471Oh3L1uTXh4UAtOqj4MP3F14Wp2fXgrbQiHCx6Bz/5hcBv2GDzXawHnkRHw/3xb"
        "fLE9Er906ICP9nbGX2/F4bt+PfBjh174tOvj+HfEAHy9NBG/3xr0hwaeRTO3nkMzn49EMyYF"
        "zXgvo5mGY9AMX+taCkJBvt+tBY0Bdb4auRoU4SveGFA9WJXcDqqnQsj5oAhf8caA6pEQagSo"
        "twuhdoDaQYVQU0C9ewi1BtROMoQaBKr+Q6hNoAjf78aAur4atQzU+l6dGgdqvxdK7QNF+H43"
        "BhTh+90YUPvbWtRQUITvd2NAEb7fjQG1dtelFoOqjXrUaFCE73djQO1VGlHTQa3djan1oPZj"
        "TegBQD0rjN4AVK7C6RlAjYhmzIPquxasB0X4WjcGVEVFsD+oCmnDuaAI3+nGgFrfPewENatE"
        "YT+o9kRzL1DP6sB9Qe08O8IDqH1sJ/gBdZ/O8AZqrxIDn6B26V3gGRThO90YUPvzWPwC6nwc"
        "/gJF+EI3BtR4j8O/oMZ1HH4HtcuNQw+gZpI4dAJqdMShH1C5iv1DV7Hoii90Y0CNlxh0CIrw"
        "hW4MqPHVCd0ytpZfrWW9texgLXtqLY6jPnKutVhiLbZZi7XWYr+13EjHsdRcbq11P4ZaDDPW"
        "wpW1sGctfGqfEE0dh3Nd41Hf8YvW4jbUfXxnLd60Fv/qv5rRJ6ABa1GFtehE92nMGrRkLeqy"
        "Fr1pn1CXPdGktahU/1WLc1GytWjbWtSunUN17CQirCVGrCVqrCWOdD6EOxJr1hJ91hKP1hKh"
        "1hKzalVVuCKurSXSreUlRIS3Ea16Pahi3/egBvFyIj5vKeLzuiI+7y3i8wIjPm8yWvXiqZK8"
        "24jPG474vOpoD9CTqsrLj/i8BYnP65D4vBdpHxJHReZNSXxemcTn3Ul8XqLE521KfF6rxOfl"
        "SnzesrSat6H6894lPi9g4vMapr3KY3QLvJiJz+uZ+Lynic8Lm/i8uYnPK5z4vMiJzxud+Lza"
        "ic87nvYAoZzOW5/2RVWxivdA8XkhFJ83Q/F5RdTeqRI34qVR7y7clHdI8XmZFJ+3SvF5vRSf"
        "90ztiwTGePPUPiQIJnkX1S6rEmyfqwTb7/Sk7ks8PcCr8fQDOfH0Bhfi6RNqC5ggzMwRfr0l"
        "rHw3iH81q4Sn/g/ae/rb"
    ),
    "triangles": (
        "eNodmgWcVVUXR8/Z+1y6BxhCpLu7pUGkREREpD5EUkJEREAaRLpbugRERES6u3Po7hmaoeNb"
        "5/r/7bXGi8577779Lnefd4yxRog1CtU4oiaAgYlDAhMXxjXxSFwTH8Y3CUh8k5DEN4lgIpOY"
        "JDJJYBKTlCQxyWAyk5wkMylIMhMBI0xKEmFSwVQmNUllImGkSUMiTVqY1qQjaU16ktZ8QNKa"
        "DDCD+ZBkMBlJBpMJZjKZSSaThWQyWUkmkw1mM9lJNpMD5jA5SQ6Ti+QwuWFuk4fkNnlhXpOP"
        "5DX5SV5TABYwBUkBU4gUMIVhYVOEFDZFSWFTDBYzxUkxUwKWMCVJCVOKlDClYWlThpQ2ZWFZ"
        "U46UNeVhefMRKW8qkPKmIqxoKpGKnPtKVGVijeE5V+E1OFOV9yMu51+JNdWI5b+tRlUnFfkd"
        "1akapDyPUIP6mJTlkT+mapLSPKOa1CekBM/3E6oWKcbrqEXVJoV5lbWpOqQA56AOVZfk5QzV"
        "pbKR3Jy5+DwX/xzi8mzi4+q83/FDVuexk2DPGjx2Muz5MY8dgT1r8tipsOcnPHYk9qzFY6fF"
        "nrV57AzYsw6PnQl71g3f0yqmHqliPjX1zWemAfnMfA4/Nw3J5+YL+IVpRL4wX5IvTGPY2HxF"
        "GpsmpLH5Gn5tmpKvTTPYzDQnzUwL2MK0JC3M/0gL0wq2Mt+QVqY1bG2+Ja1NG9LatIVtTTvS"
        "1rQnbU0H2MF0JB3Md6SD6QQ7mc6kk+kCu5iupIv5nnQx3WA38wPpZrrD7uZH0t30IN3NT6S7"
        "6Ql7mp9JT9OL9DS9YW/Th/Q2v5Depi/pbfrBfqY/6WcGwAFmIBlgBsFBZjAZZIbAIWYoGWJ+"
        "JUPMMDjM/EaGmeFwuBlBhpuRcKQZRUaa0WSkGQPHmLFkDGd9LFWfZzuO593IjA/P/3gzAU4I"
        "35cJZiLvx2dmEvmM/2MSNZmM4TdNpqaQkTzOFGoqGc7jT6WmkWE8r2nUdDKEZz2dmkEG8Wpm"
        "UDPJAF7lTOp30o9X/zs1i/TmDM2iupGenL/G9IB/Dl/wbBrjybzrjUNO5rGbYc8pPHYL7DmV"
        "x26FPafx2K2x53Qeuy32nMFjd8CeM3nsTtjzdx67C/acFb6348xsMs7MMXPNPDOfzDMLzEJq"
        "EVlgFsPFZglZbP6Af5il/Oky/mQBnM+RpWY5WWr+hH+aFXCF+YusMCvhSvM3v38O/Bv+xZmf"
        "aFaRieYfMtGsJhPNv2SiWUMmmv/gf2Yt+c+sg+vMerLObIAbzEaywWyCm8xmsslsgVvMVrLF"
        "bIPbzHayzeyAO8xOssPsgrvMbrLL7IF7zF6yx+wje8x+uN8cIPvNQbLfHIKHzGFyyByBR8xR"
        "csQcg8fMcXLMnCDHzEl40pwiJ00UjDKnSZQ5Q6LMWXjWnCNnzXly1lyAF8xFcsFcIhfMZXjZ"
        "XCGXzVVy2VyD18x1cs3cINfMTZ7brfDZ3jK3yS1zB94xd8kdEw2jTQyJNvfgPXOf3DMP4APz"
        "kDwwj+Aj85g8Mk/gE/OUPDGxMNY8I7HmOYk1L0iseUlizSsSa17D1+YNeW3ewrfmHXkfHnlv"
        "jH1D+X/E+iNilYh10NmAOBsHxrFxYVwbj8S18WF8m4DEtwlhQpsIJrKJSSKbBCaxSWFSm4wk"
        "tclhcpsCprARJIVNCVPaVCR1eCS1jbTz6OI0No2da9LatDCdTQfT2/TwA/iBzQAz2A9JBpsR"
        "ZrSZYCabmWSyWWAWm5VksdlgNpsdZrc5SHabE+a0uWAum5vksnlgHpuX5LH5YD6bH+a3BUh+"
        "WxAWtIVIQVsYFrZFYBFblBSxxWAxW9yWsCVhcVgKlrKlSdHweHFbhhS3Ze2nppz1f7OUs+VJ"
        "OfsR/MhWgBVsRVLBVoKVbGVY2VYhlW1VWNVWg9VsdVKN31WdqkHK2I9JGX5zVVPT+jurmvYT"
        "/ImtRWqHR2rbOriOrUvq2Hqwnv2U1LP1YX37GalvG8AG9nPSwDaEDe0XpKFtBBvZL0kj2xg2"
        "tl+RxrYJbGK/Jk1sU9jUNiNNbXPY3LawLe3/YAvYCray35BWtjVsbb8lrW0b2Ma2JW1sO9jO"
        "tiftbAfYwXbk/2xpvyMtbSfYyXYmnWwX2MV2JV3s9/B72418b3+AP9ju5Af7I/zR9iA/2p/g"
        "T7Yn+cn+DH+2vcjPtjfsbfuQX8Ijv9i+sK/tB/vZ/qSfHQAH2IFkgB1EBtjBZIAdQgbYoWSA"
        "/ZUMsMPgMPsbGWaHk2F2BBxhR5IRdhQcZUeTUXYMGWXHwrF2HBlrx5OxdgKcYCeSCXYSmWAn"
        "w8l2Cplsp5LJdhqZbKdzfjraGaSjnQln2t/JTDsLzrKz4Ww7h8y2c+FcOw/Os/PJPLsALrAL"
        "4UK7iCy0i+FiuwQusX+QJXYpXGqXkeX89A3vZwv7p11h/yIr7Eq40v5NVtpVcJX9h6yyq+Fq"
        "+y9ZbdfANfY/ssauhWvtOrLWrofr7Qay3m6EG+0mstFuhpvtFrLZboVb7Tay1W6H2+0Ost3u"
        "JNvtLrjL7ia77B64x+4le+w+uM/uJ/vsAXjAHiQH7CF4yB4mh+wReMQeJUfsMXjMHifH7Al4"
        "wp4kJ+wpeMpGkVP2NDxtz5DT9iw8a8+Rs/Y8PG8vkPP2IrxoL5GL9jK5aK/AK/YquWKvwWv2"
        "Orlmb8Ab9ia5YW/BW/Y2uWXvkFv2Lrxro8ldGwNj7D0SY++TGPsAPrAPyQP7CD6yj8kj+wQ+"
        "sU/JExsLY+0zEmufk1j7Ar6wL8kL+wq+sq/JK/sGvrFvyRv7Dr6z78k7BrP3FBd8LhoCRZSI"
        "OOgkIE7iwDgSl8SReDCexCfxJAFMIAlJAkkEE0likkiSwCSSlCSRZDCZJCfJJAVJJhEwQlKS"
        "CEkFU0lqkkoiYaSkIZGSFqaVdCStpIfp5QOSXjLADPIhySAZYUbJRDJKZphZspDMkhVmlWwk"
        "q2SH2SWH5JRckpvkkjwwj+QleSQfzCf5ST4pAAtIQVJACsFCUpgUkiKwiBQlRaQYLCbFSTEp"
        "AUtISVJCSsFSUpqUkjKwjJQlZaQcLCflSTn5iJSTCrCCVCQVpBKsJJVJJakCq0hVUkWqwWpS"
        "nVSTGrCGfExqSE1YUz4hNaUWrCW1SS2pA+tIXVJH6sF68impJ/VhffmM1JcGsIF8ThpIQ9hQ"
        "viANpRFsJF+SRtKYNJKv4FfShHwlX8OvpSn5WprBZtKcNJMWsIW0JC3kf6SFtIKt5BvSSlrD"
        "1vItaS1tSGtpC9tKO9JW2sP20oG0l46wo3xHOkon2Ek6k07ShXSSrrCrfE+6SjfYTX4g3aQ7"
        "7C4/ku7SA/aQn0gP6Ql7ys+kp/SCvaQ36SV9YB/5hfSRvrCv9CN9pT/sLwNIfxkIB8ogMlAG"
        "w8EyhAyWoXCo/EqGyjA4TH4jw2Q4GSYj4AgZSUbIKDhKRpNRMgaOkbFkjIyD42Q8GScT4ASZ"
        "SCbIJDhJJpNJMgVOkalkikyD02Q6mSYz4AyZSWbI7/B3mSV17Wzxf7/Pljl4jjDMQz/XzxE/"
        "6c+RuXiu+BWAueJXA+aKXx+YK37FYK7Mw/PEryTME7+qME/8OsM88SsP82Q+ni9+LWK++NWJ"
        "+eJXKuaLX7uYL34dY774lY354tc65otf95gvfiVkvlRhcp4vC/ACKcddzgJZiBfKR9zrLJRF"
        "eJFU4NnXtYtlMfwUf2qXyBL4Gf7M/iF/wM/x53apLIVf4C/sMlkGv8Rf2uWyHH6Fv7J/yp/w"
        "a/y1XSErYDPczP4lf8Fv8Dd2payE3+Jv7d/yN2yL29pVsgq2x+3tP/IPnIFn2NWyGv6Of7f/"
        "yr9wDp5j18gaOB/Pt//Jf3ARXmTXylr4B/7DrpN1cDmv/VPORQVebyXu6hbJerxeKnNXt142"
        "4A1SlXu7DbIRb5Rq3NttlE14k/g7xk1SgrvHTbIZb5aS3Fluli14i5Ti/nKLbMVbxd9nbpVt"
        "eJv4O9Jtsh1vF3+/ul124B3i72N3yE68U/xd7k7ZhXeJv/vdJbvxbvH3xrtlD94j/s55j+zF"
        "e8XfUe+VfXif+PvtfbIf7xd/N75fDuAD4u/PD8hBfFD8HftBOYQPib+HPySH8WGZx0R6WI7g"
        "I+KnziOymFn0iBzFR+UPJtKjcgwfk6VMocfkOD4ufzKLHpcT+ISsYBY9ISuZRU/ISXxS/DR6"
        "Uk7hU+Ln31PiVzlOiV/3OCV+DeSUROEo8WsjUeJXS6LEr5xEiV9LiRK/rhIlfqUlSvyqS5T4"
        "dZgo8SszUXIanxa/VnNa/OrNafHrOafFr/CcljP4jPg1nzPiV4HOiF8ROiNn8VkZb8bDCWYC"
        "nMg8fFbO4XPyH/PwOTmPz8s65uHzcgFfkA3MwxfkIr4om5iHL8olfEm2MA9fksv4smxjHr4s"
        "V/AV2cE8fEWu4quyi3n4qlzD12QPk/A1uY6vy35m4OtyA9+QQ8zAN+QmvilHmIFvyi18S44x"
        "/d6S2/i2nGT6vS138B2JYu69I3fxXTnLxHtXonG0XGDWjZYYHCOXmXJj5B6+J9eYb+/JfXxf"
        "bpoH8jD8e/Zh+DduTnlEcvJvj6jH5KE8gU/kKXkisTBWnpFYeQ6fywvyXF7Cl/KKvJTX8LW8"
        "Ia/lLXwr78hbeQ/f+8Vkfc/Iahha/Y2LVYWqjqgGMNA4JNC4MK7GI3E1PoyvCUh8TQgTaiKS"
        "UBPDxJqEJNakMKkmI0k1OUyuKUhyjYARmpJEaCqYSlOTVBoJIzUNidS0MK2mI2k1PUyvH5D0"
        "mgFm0A9JBs0IM2omklEzw8yahWTWrDCrZiNZNTvMrjlIds0Jc2ouklNzw9yah+TWvDCv5iN5"
        "NT/MrwVIfi0IC2ohUlALw8JahBTWorCoFiNFtTgsriVIcS0JS2opUlJLw9JahpTWsrCsliNl"
        "tTwsrx+R8loBVtCKpIJWgpW0MqmkVWAVrUqqaDVYTauTaloD1tCPSQ2tCWvqJ6Sm1oK1tDap"
        "pXVgHa1L6mg9WE8/JfW0Pqyvn5H62gA20M9JA20IG+oXpKE2go30S9JIG8PG+hVprE1gE/2a"
        "NNGmsKk2I021OWyuLUhzbQlb6v9IS20FW+k3ZJb4I7OkNWwd/pet9Vv4bfgbvtU2sE34m9to"
        "W9g2fMS22g62C59JO20P24fPsL12gB3CZ95BO8KO4SvqqN/B78JX+p12gp3CM9BJO8PO4Znp"
        "rF1gl/CMddGusGt4Jrvq9/D78Ax/r91gt/DMd9Mf4A/hO/KDdofdw3equ/4IfwzfwR+1B+wR"
        "vrM99Cf4U/iO/6Q9Yc+wE3rqz/DnsEN+1l6wV9g5vbQ37B12VG/tA/uEndZHf4G/hB34i/aF"
        "fcPO7Kv9YL+wY/tpf9g/7OT+OgAOCDt8gA6EA8POH6iD4KDwEzFIB8PB4SdlsA6BQ8JP0BAd"
        "CoeGn6yh+iv8NfzE/arD4LDwkzhMf4O/hZ/Q33Q4HB5+cofrCDgi/ESP0JFwZPhJH6mj4Kjw"
        "CjBKR8PR4ZVhtI6BY8IrxhgdC8eGV5KxOg6OC68w43Q8HB9eecbrBDghvCJN0Ilwov+CBU6C"
        "k9RfwSbpZDxZ/ZVtsk7BU9Rf8aboVDxV/ZVwqk7D09RfIafpdDxd/ZVzus7AM9RfUWfoI+4K"
        "f6dLW+vv8i01A36rM6QNNQ220WnSlpoC2+oUaUdNgu10krSnJsD2OkE6UONgBx0nHakxsKOO"
        "ke+oUfA7HSWdqBGwk46QztQw2FmHSRdqKOyiQ6UrNRh21cHyPTUQfq8DpRvVH3bT/vID1Rf+"
        "oH2lO9UHdtc+8iPVC/6ovaQH1RP2UO7sKe7z6U7u86nusKd2l5+pbvBn7Sa9qK6wl3aV3lQn"
        "2Fs7SR+qI+yjHeUXqj38RdtLX6ot7KttpR/VGvbT1tKfagX7aysZQLWAA7SFDKSawYHaTAZR"
        "X8NB+rUMpr6Cg/UrGUI1gkO0kQylGsKh2lB+pRrAX7WBDKPqw2FaX36j6sHftJ4Mp+rA4VpH"
        "RlC14AitJSOpmnCk1pRRVA04SmvIaKoaHK3VZAxVBY7RKjKWqgTHaiUZR1WA47SCjKfKwfFa"
        "TiZQZeAELSMTqVJwopaiK0sxz06iR0vQlSWYcyfTp8XoymLMv1Po0yJ0ZRHm4qn0aSG6shDz"
        "8jT6tABdWYA5ejp9mo+uzMd8PYM+zcPf/Xm4F3gk3+hMrqazZKbOZK5hmtHf+Wmmp84is9Uf"
        "ma1z4Bz109Ac9fPRHJ2L56qfm+bqPDxP/Tw1T+fj+ernrPm6AC9QP38t0IV4ofq5bKEuwovU"
        "z2uLdDFerH6CW6xL8BL1k90S/QP/oX7i+0OX4qXqJ8GlugwvUz8hLtPleLn6yXG5/on/VD9R"
        "/qkr8Ar1k+YK/Qv/pX4C/UtX4pXqJ9OV+jf+W/3E+reuwqvUT7Kr9B/8j/oJ9x9djVern3xX"
        "67/4X/Wz8L+6Bq9RPyOv0f/wf+pn5/90LV6rfqZeq+vwOvWz9jpdj9ern77X6wa8Qf1UvkE3"
        "4o3qp/WNuglvUj+/b9LNeLP6uX6zbsFb1M/7W3Qr3qp+HWCrbsPb1K8PbNPteLv6FYPtugPv"
        "UL+SsEN34p3qVxh26i68S/3Kwy7djXerX5HYrXvwHvUrFXt0L96rfgVjr+7D+9SvbOzT/Xi/"
        "+hWP/XoAH1C/EnJAD+KD6ldIDuohfEj9yskhPYwPq19ROaxH8BH1Ky1H9Cg+qn7t5agew8fU"
        "r8kc0+P4uPq1muN6Ap9Qv4ZzQk/ik+rXdk7qKXxK/ZrPKY3CUerXgqL0ND6tfo3otJ7BZ9Sv"
        "HZ3Rs/is+jWls3oOn1N/D3xOz+Pz+kBm6wU6eg6cS12Ec+E86hKcB+dTl+F8uIC6AhfAhXpV"
        "I+0Vfoq0C/m3SLuIjo60qXFqu5iOTm1T4VR2CR2dyqbEKe0fdHRKmwKnsEvp6BQ2OU5ul9HR"
        "yW1SnNQup6OT2iQ4if2Tjk5iE+FEdgUdncgmxAntX3R0Qhsfx7cr6ej4Ni6Oa/+mo+PaODiO"
        "XUVHx7EOO/sPHe2sYLGr6WixFlv7Lx1trcHGrqGjjX1v1uh78x8d/d68w+/MWjr6nXmL35p1"
        "dPRb8xq/Nuvp6NcmFseaDXR0rHmCn5iNdPQT8wg/Mpvo6EfmAX5gNtPRD8w9fM9soaPvmWgc"
        "bbbS0dHmDr5jttHRd8wtfMtsp6NvmQP4gNlBRx8wB/FBs5OOPmgO48NmFx192BzFR81uOvqo"
        "OY6Pmz109HFzAp8we+noE+YUPmX20dGnzGl82uyno0+bM/iMOUBHnzHn8DlzkI4+Z87j8+YQ"
        "HX3eXMQXzWE6+qK5hC+ZI3T0JXMFXzFH6egr5iq+ao7R0VfNdXzdHKejr5sb+IY5QUffMDfx"
        "TXOSjr7JTHZSmc34+RpdfQpeh9fp6ih4A96gq0/Dm/AmXX0G3oK36Oqz8Da8TVefg+e5Kk/n"
        "ur3K3FH/LfwdvYvvan1TH/rv7u+q/zb/rkbjaPXf70er/8Y/Wv0egGj1uwKi1e8QiFa/ZyBa"
        "Y3CM+r0EMep3F8So328Qo37vQYz6fQgx6ncmxKjfpRCjft9CjPo9DDHq9zPE6DgzDs4xc6D/"
        "5jpG7+F76r/Xvqf38X3134Df1wf4gS7iea8yD/Uh/Af/Yx7pI7garzaP9TH8F/9rnugTuAav"
        "MU/1KVyL15pYjYXr8XrzTJ/BjXijea7P4Wa82bzQF3Ar3mpe6ku4HW83r/QV3Il3mtf6Gu7G"
        "u80bfQP34r3mrb6F+/A+807fwdv4tnmv7+FdfNf4TVR3TQyOMXz84H1834gT+BA/NP5m9KF5"
        "jB8bxz+PzVP81AQugM/wMxPHxYHP8XMT18WFL/ALE8/Fgy/xSxPfxYev8CuTwCWAb/Abk9Al"
        "hGoTOrWJXCIY4MAmdolhPBzPJnFJYAKcwCZ1SWFinNgmc8k8vW1ylxxG4Ah7lStehI20xWwK"
        "579XTeEicITz33tGuOr8ezGb0qWERXARm8qlgoVxYZvapYYFcUEb6SJhfpzfpnFpYD6cz6Z1"
        "aWEenMemc+lgLpzLpnfpYU6c037gPoDZcXabwWWA2XA2+6H7EGbBWWxGlxFmwplsJkf8d9Eu"
        "o83sMsMMOIPN4rLAD/AHNqvLCuearG4uPfhA55qFeKFZZOabZWYuWcaRGvbj8Nvkj21ZO91O"
        "ttlcNjfZZnfZ4QQ8weZwOeBYPNbmdDnhKDzK5nK54Ag8wuZ2ueEwPMzmcXngADzA5nV5YT/c"
        "z+Zz+WBf3Nfmd/nhL/gXW8AVgH1wH1vQFYS9cW9byBWCP+OfbWFXGP6Ef7JFXBH4I/7RFnVF"
        "4Q/4B1vMFYPf4+9tcVccdsFdbAlXAnbCnWxJVxK2xC1tKVcKtsAtbGlXGjbHzW0ZVwY2xU1t"
        "WVcWNsFNbDlXDjbGjW15Vx42wo3sR+4j2BA3tBVcBdgAN7AVXUVYH9e3lVwlWA/Xs5VdZVgH"
        "17FVXBVYG9e2VV1VWAvXstVcNfgJ/sRWd9VhTVzT1nA1YFVTw1U1H7uPocMu3NMYLzwSz9R0"
        "NWECnCDczZg4PJLYJMVJw72LKcIjKUxKnNJ84j6BqXHqcL9iuvBIOpMepw93Kn4YHvnQZMQZ"
        "w92JWcIjWUxWnDXcw1be+iPlbS1XC1bEFW1tVxtWwVX4JEXA6raOq+v8N7x1nf+u909bz9Xj"
        "p7qwrvuU1HX1YX33GanvGsAG7nPSwDWEDd0XpKFrBBu5L0kj1xg2dl+Rxq4JbOK+Jk1cU9jU"
        "NSNNXXPY3LUgzV1L2NL9j7R0rWAr9w1p5VrD1u5b0tq1gW1cW9LGtYPtXHvSznWAHVxH0sF9"
        "B79znch3rjPs7LqQzq4r7Oq+J11dN9jN/UC6ue6wu/uRdHc9YA/3E+nhesKe7mfS0/WCvVxv"
        "0sv1gX3cL6SP6wv7un6kr+sP+7sBpL8bCAe6QWSgGwwHuyFksBsKh7pfyVA3DA5zv5Fhbjgc"
        "7kaQ4W4kHOlGkZFuNBztxpDRbiwc68aRsW48HO8mkPFuIpzoJpGJbjKc7KaQyW4qnOqmkalu"
        "OpzuZpDpbiac6X4nM90sOMvNJrPcHDjHzSVz3Dw4z80n89wCuMAtJAvcIrjILSaL3BK4xP1B"
        "lrilcKlbRpa65XC5+5MsdyvgCvcXWeFWwpXub7LSrYKr3D9klVsNV7t/yWq3Bq5x/5E1bi1c"
        "69aRtW49XO82kPVuI9zoNpGNbjPc7LaQzW4r3Oq2kRzij+SQ7XB7+F9udzvgjvA37HA74c7w"
        "N+90u+Cu8BF3ud1wd/hMdrs9cE/4DPe4vXBv+Mz3un1wX/iK9rn9cH/4Sve7A/BAeAYOuIPw"
        "YHhmDrpD8FB4xg65w/BweCYPuyPwSHiGj7ij8Gh45o+6Y/BY+I4cc8fh8fCdOu5OwBPhO3jC"
        "nYQnw3f2pDsFT4Xv+CkXBaPCTohyp+HpsENOuzPwTNg5Z9xZeDbsqLPuHDwXdto5dx6eDzvw"
        "vLsAL4SdecFdhBfDjr3oLsFLYSdfcpfh5bDDL7sr8ErY+VfcVXg1/ERcddfgtfCTcs1dh9fD"
        "T9B1dwPeCD9ZN9xNeDP8xN10t+Ct8JN4y92Gt8NP6G13B94JP7l33F14N/xE33XRMDr8pEe7"
        "GBgTXgFi3D14L7wy3HP34f3winHfPYAPwivJA/cQPgyvMA/dI/govPI8co/h4/CK9Ng9gU/C"
        "K9UT9xQ+Da9gT10sjA2vbLHuGXwWXvGeuefweXglfO5ewBfhFfKFewlfhlfOl+4VfBVeUV9x"
        "bc0h2enS7S677KCywh0uq+ykMsOdLrPsojLCXS6j7KYywN0ug+yh0sM9Lr3spdLCvS6t7KMi"
        "4T4XKfupVHC/SyUHqAh4wEXIQSoZPOiSySEqCTzkkshhKhE87BLJESoBPOISyFEqHjzq4skx"
        "Kg485uLIccrB487JCUrgCXTS+S+mT9KdRk5R7+wpuvOdjaLewCj3xp6mXsHT7pU9Q72AZ9wL"
        "e5aKhWddrD1HPYHn3BN7nnoEz7tH9gL1AF5wD+xFKgZedDH2EnUXXnJ37WXqFrzsbtkr1A14"
        "xd2wV6lrkO6016grnu6KvU5dhNfdRXuDOg9vuPP2JnUW3nRn7S3qNLzlTtvb1Cl4252yd6gT"
        "8I47Ye9Sx+Bdd8xGU0dgtDtiY6hDMMYdsveoA/CeO2DvU/vgfbfPPqD2wAduj31I7YIP3S77"
        "iNoOH7nt9jG1FT52W+0TajN84jbbp9RG+NRttLHUehjr1ttn1Fr4zK21z6k18LlbY19Qq+EL"
        "t9q+pFbBl26VfUWthK/cSu4BVnIvUI8r6ms6NYe8dtkki2STN+4NP72Gr91b8s75I+/ce/je"
        "+X04753fmfPemeBDMYHfsWMCi23gd/LYQLAEfoePBIo18Dt/lHEktbjA7whyQYCDwO8UCoI4"
        "OE7g9w7FCeLiuIHfUxQ3iIfjBX6vUbwgPo4f+D1I8YMEOEHg9ybxE04Y+D1LCYNEOFHg9zIl"
        "ChLjxIFfmk8cJMFJAr/3KUmQFCcN/J6opEEynCzwe6WSBclx8sDvoUoepMApAr+3KkUQgSMC"
        "v+cqIkiJUwZ+F1bKIBVOFfjdWamC1Dh14HdtpQ4icWTgd3NFBmlwmsDv8koTpMVpA7/vK22Q"
        "DqcL/H6wdEF6nD7w+8TSBx/gDwK/c+yDIAPOEPgdZRmCD/GHgd9p9mGQEWcM/A60jEEmnCnw"
        "O9MyBZlx5sDvVcscZMFZAr+HLUuQFWcN/N62rEE2nC3we96yBdlx9sDvhcse5MA5Ar9HLkeQ"
        "E+cM/N65nEEunCvwe+pyBblx7sDvtcsd5MF5Ar8HL0+QF+cN/N68vEE+nC/we/byBflx/sDv"
        "5csfFMAFAr/Hr0BQEBcM/K6/gkEhXCjwuwELBYVx4cDvEiwcFMFFAr97sEhQFBcN/K7CokEx"
        "XCzwuw2LBcVx8cDvQiwelMAlAr87sURQEpcM/K7FkkEpXCrwuxlLBaVx6cDfA5cOyuAyQR16"
        "umzwnp4uG5igbFAOGmip8n5DNBTqI99QUKkKUKEL1slyW4GflluGbEhDw2V4mY1DRy+zS/FS"
        "G5eOXmqX4CU2Hh29xC7Gi218OnqxXYgX2gR09EK7AC+wCenoBXYenmcT0dHz7Fw81yamo+fa"
        "2Xi2TUJHz7az8Cy6OCmciWfSxclgR9yRLk4OO+AOdHEK2A63o4sjYBvchi5OCVvj1nRxKtgK"
        "t6KLU8P/4f/RxZHwO/wdXZwGdsad6eK0sCvuSheng91wN7o4PeyOu9PFH8AeuAddnAH2xD3p"
        "4g9hL9yLLs4I++P+dHEmOBAPpIszw0F4EF2cBQ7Gg+nirHAIHkIXZ4ND8VC6ODv8Ff9KF+eA"
        "v+Hf6OKccDgeThfngiPxSLo4NxyNR9PFeeAYPIYuzgvH4XF0cT44Ho+ni/PDiXgiXVwATsKT"
        "6OKCcAqeQhcXglPxVLq4MJyGp9HFReB0PJ0uLgqzuaJBNleRnyvS1cVgJViJri4OK8PKdHUJ"
        "WAVWoatLwqqwKl1dClaD1ejq0rBMkIkr9xtXIVjl/N6kVdyDr5OV3JWv4thq7rwr0Lur3UfB"
        "Gu68P6Kn17jywVruvMvT62tdObp/LZ+C9dx/lw3ewXfcfW+Eb+Fb7r43w9fwNffgW+E2fv8K"
        "5/dErWAOWCvLmQzWylLnd0wtZWL4T5YwQyxipvBHFji/q2oB08Yamcf8MYd5xB+Z5fzOq1lM"
        "Kv/KTGaXf2W68/uypjPTrJapTDmrZbLzu7YmM/38IxOZh/6R8c7v6RrPnLRKxjI5rZLRzu/4"
        "Gs1E9beMZMb6W4Y7v9YxnNkrP+XXQIYxk+WjBsPBzq+QDGZ6y0v1h/2dXz/pz5yXh+oD+zi/"
        "utKHiTA31RP2dH7tpSezYy6qO+kWHunm/PpMN+bOnFRn2Nn51ZvOTKg5qA6kXXiknfMrPO2Y"
        "brNTrUmr8Egr59d/WjEZZ6Oaw+b0RsWgOTN0xaCpq0RPNGW2rhQ0cZXpiSbM3JWDxq4KPdHY"
        "VaUbGjORVw0auWp0QyMm9WpBQ1eGvmjIBF8maODqkAZM9nWoupyf/M7vl8vvCuACriAs6Pxu"
        "uoKuEC7k/C67Qq4wLuz87rvCrggu4vyuvCKuKC7q/G69oq4YLub8Lr5irjgu7vzuvuKuBC7h"
        "/K6/Eq4kLun8bsCSrhQu5UrD0m62zIZlcBk3R+bAsrismytzYTlczs2TebA8Lu/my3z4Ef7I"
        "LZAFsAKu4BbKQlgRV3SLZBGshCu59X5HnquMK7sNfkeeq4KruI2yEW6STbAqruo2y2ZYDVdz"
        "W2QLrI6ru62yFW6TbbAGruG2y3b4Mf7Y7ZAdsCau6XbKTvgJ/sTtkl2wFq7ldstueE93yz3d"
        "I3tgDI7RvbIXRuNo3Sf74F18V/fLfngH39EDcgA+xA/1oByEh+QQfIQf6WE5DB/jx3pEjsAn"
        "+IkelaPwmByDT/FTPS7HYSyO1RNyAj7Dz/SknITP8XM9JafgC/xCoyQKvsQv9bSchq/wKz0j"
        "Z+Br/FrPyln4Br/Rc3IOvsVv9bych+/wO32v97SWu6/3YW1c2/kV0douAkc4v1Ia4VLAFM6v"
        "oKZwKWFK51dWU7pUMJVfb4WpYWrnV2JTu0gY6fwKbaRLA9M4v3KbxqWFaZ1f0U3r0sF0Lr07"
        "L+/1glyAxl0Q4y7KRWixdZfkEhQs7rJchorVXZEr0GHnrspVGODAXZNrMA6O467LdRgXx3U3"
        "5AaMh+O5+C6By6t+FT2v5sa59abclNyaE+fU7JrQFVS/rl5Q8+P8mlcTuaLqV9eLamFcWAtq"
        "YldS/Rp7SS2Oi2tRTeLKql9pL6ulcWktqUldJfXr7ZW0Aq6g5TWZq6Z+1b2aVsFVtJImd7XU"
        "r73X0pq4ptbQq1pf/Qp8fa2H62kdvaIN1a/DN9QGsAF/3pBjjcgVvQwva2NyWS/BS9qEXNKL"
        "8KJegBe0Kbmgs+FsbU5m6yw4S1uSWToTztRWZKZ+w6PV4lFraDWeTXkty/O+Kdn1ltyCWXFW"
        "zQwz6225DTPijJoBZtA7cgemx+k1LUyrd+UujMSRmgqm0miJhhE4QpOTpOGRpBojMTAxTqwJ"
        "SfzwSHy9J/dgXByXG7p7jCn35T5UrGqh1WvE6nu5Rl3X6/Atfis39AZ8jV/LTb0Jb+kt+BK/"
        "lNt6Gz7Hz+W8noexOFYekFh5Ap/IQ7rihsR3/wfOt4vW"
    ),
}

HAUSDORFF_SAMPLES = 2000


# ═══════════════════════════════════════════════════════════
# Test helpers
# ═══════════════════════════════════════════════════════════

_SURFACE_NAMES = {
    GeomAbs_Plane: "Plane",
    GeomAbs_Cylinder: "Cylinder",
    GeomAbs_Cone: "Cone",
    GeomAbs_Sphere: "Sphere",
    GeomAbs_Torus: "Torus",
    GeomAbs_BSplineSurface: "BSpline",
}


def _get_face_inventory(shape):
    explorer = TopExp_Explorer(shape.wrapped, TopAbs_FACE)
    faces = []
    while explorer.More():
        face = TopoDS.Face_s(explorer.Current())
        adaptor = BRepAdaptor_Surface(face)
        stype = adaptor.GetType()
        type_name = _SURFACE_NAMES.get(stype, f"Other({stype})")
        props = GProp_GProps()
        BRepGProp.SurfaceProperties_s(face, props)
        info = {"type": type_name, "area": props.Mass()}
        if stype == GeomAbs_Cylinder:
            info["diameter"] = adaptor.Cylinder().Radius() * 2
        elif stype == GeomAbs_Sphere:
            info["radius"] = adaptor.Sphere().Radius()
        elif stype == GeomAbs_Torus:
            info["major_r"] = adaptor.Torus().MajorRadius()
            info["minor_r"] = adaptor.Torus().MinorRadius()
        elif stype == GeomAbs_Cone:
            info["semi_angle_deg"] = math.degrees(adaptor.Cone().SemiAngle())
        faces.append(info)
        explorer.Next()
    faces.sort(key=lambda f: (f["type"], -f["area"]))
    return faces


_CURVE_NAMES = {
    GeomAbs_Line: "Line",
    GeomAbs_Circle: "Circle",
    GeomAbs_Ellipse: "Ellipse",
    GeomAbs_BSplineCurve: "BSpline",
}


def _get_edge_inventory(shape):
    explorer = TopExp_Explorer(shape.wrapped, TopAbs_EDGE)
    edges = []
    while explorer.More():
        edge = TopoDS.Edge_s(explorer.Current())
        adaptor = BRepAdaptor_Curve(edge)
        ctype = adaptor.GetType()
        type_name = _CURVE_NAMES.get(ctype, f"Other({int(ctype)})")
        length = GCPnts_AbscissaPoint.Length_s(adaptor)
        info = {"type": type_name, "length": length}
        if ctype == GeomAbs_Circle:
            info["radius"] = adaptor.Circle().Radius()
        edges.append(info)
        explorer.Next()
    edges.sort(key=lambda e: (e["type"], -e["length"]))
    return edges


def _cross_section_props(shape, axis_pos, plane_maker, uv_axes):
    # Return area, centroid, and 2D shape moments for a cross-section.
    _axis_idx = {"X": 1, "Y": 2, "Z": 3}
    u_idx = _axis_idx[uv_axes[0]]
    v_idx = _axis_idx[uv_axes[1]]
    zero = {"area": 0.0, "centroid_u": 0.0, "centroid_v": 0.0,
            "Iuu_2d": 0.0, "Ivv_2d": 0.0}
    plane = plane_maker(axis_pos)
    section = BRepAlgoAPI_Section(shape.wrapped, plane, False)
    section.ComputePCurveOn1(True)
    section.Approximation(True)
    section.Build()
    if not section.IsDone():
        return zero

    result_shape = section.Shape()
    edges_seq = TopTools_HSequenceOfShape()
    wires_seq = TopTools_HSequenceOfShape()
    edge_exp = TopExp_Explorer(result_shape, TopAbs_EDGE)
    while edge_exp.More():
        edges_seq.Append(edge_exp.Current())
        edge_exp.Next()
    if edges_seq.Length() == 0:
        return zero

    ShapeAnalysis_FreeBounds.ConnectEdgesToWires_s(
        edges_seq, 1e-4, False, wires_seq
    )
    total_area = 0.0
    total_cu = 0.0
    total_cv = 0.0
    total_Iuu = 0.0
    total_Ivv = 0.0
    for w_idx in range(1, wires_seq.Length() + 1):
        wire = TopoDS.Wire_s(wires_seq.Value(w_idx))
        try:
            face_maker = BRepBuilderAPI_MakeFace(plane, wire, True)
            if face_maker.IsDone():
                face_shape = face_maker.Face()
                face_props = GProp_GProps()
                BRepGProp.SurfaceProperties_s(face_shape, face_props)
                a = abs(face_props.Mass())
                com = face_props.CentreOfMass()
                u = getattr(com, uv_axes[0])()
                v = getattr(com, uv_axes[1])()
                total_area += a
                total_cu += u * a
                total_cv += v * a
                mat = face_props.MatrixOfInertia()
                total_Iuu += mat.Value(u_idx, u_idx)
                total_Ivv += mat.Value(v_idx, v_idx)
        except Exception:
            continue
    cu = total_cu / total_area if total_area > 1e-9 else 0.0
    cv = total_cv / total_area if total_area > 1e-9 else 0.0
    return {"area": total_area, "centroid_u": cu, "centroid_v": cv,
            "Iuu_2d": total_Iuu, "Ivv_2d": total_Ivv}


def _radial_distance(shape, origin, direction, max_r=20.0):
    line = gp_Lin(origin, direction)
    intersector = IntCurvesFace_ShapeIntersector()
    intersector.Load(shape.wrapped, 1e-6)
    intersector.PerformNearest(line, 0.0, max_r)
    if intersector.NbPnt() > 0:
        pt = intersector.Pnt(1)
        dx = pt.X() - origin.X()
        dy = pt.Y() - origin.Y()
        dz = pt.Z() - origin.Z()
        return math.sqrt(dx * dx + dy * dy + dz * dz)
    return None


# ═══════════════════════════════════════════════════════════
# Hausdorff distance helpers
# (copied verbatim from cad_fingerprint.hausdorff / .analyze)
# ═══════════════════════════════════════════════════════════

def decode_mesh(payload: dict) -> tuple[list, list]:
    """Decode an :func:`encode_mesh` payload back into (vertices, triangles)."""
    if payload and payload.get("truncated"):
        raise ValueError(
            "this fingerprint's surface mesh was truncated for display; "
            "re-run the analysis with --json to write the full mesh"
        )
    if not payload or not payload.get("vertex_count"):
        return [], []
    lo = payload["bbox_min"]
    hi = payload["bbox_max"]
    scale = [(hi[a] - lo[a]) / 65535.0 if hi[a] > lo[a] else 0.0
             for a in range(3)]

    vbuf = zlib.decompress(base64.b64decode(payload["vertices"]))
    raw = struct.unpack(f"<{len(vbuf) // 2}H", vbuf)
    vertices = [
        (lo[0] + raw[i] * scale[0],
         lo[1] + raw[i + 1] * scale[1],
         lo[2] + raw[i + 2] * scale[2])
        for i in range(0, len(raw), 3)
    ]

    tbuf = zlib.decompress(base64.b64decode(payload["triangles"]))
    if payload.get("index_bits", 16) == 16:
        flat = struct.unpack(f"<{len(tbuf) // 2}H", tbuf)
    else:
        flat = struct.unpack(f"<{len(tbuf) // 4}I", tbuf)
    triangles = [flat[i:i + 3] for i in range(0, len(flat), 3)]
    return vertices, triangles


def _point_triangle_distance2(p, a, b, c) -> float:
    """Squared distance from point p to triangle (a, b, c).

    Voronoi-region algorithm (Ericson, *Real-Time Collision Detection*):
    classify p against the triangle's vertex/edge/face regions, then
    project onto whichever feature is closest.
    """
    abx, aby, abz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    acx, acy, acz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    apx, apy, apz = p[0] - a[0], p[1] - a[1], p[2] - a[2]

    d1 = abx * apx + aby * apy + abz * apz
    d2 = acx * apx + acy * apy + acz * apz
    if d1 <= 0.0 and d2 <= 0.0:
        return apx * apx + apy * apy + apz * apz

    bpx, bpy, bpz = p[0] - b[0], p[1] - b[1], p[2] - b[2]
    d3 = abx * bpx + aby * bpy + abz * bpz
    d4 = acx * bpx + acy * bpy + acz * bpz
    if d3 >= 0.0 and d4 <= d3:
        return bpx * bpx + bpy * bpy + bpz * bpz

    vc = d1 * d4 - d3 * d2
    if vc <= 0.0 and d1 >= 0.0 and d3 <= 0.0:
        denom = d1 - d3
        v = d1 / denom if denom != 0.0 else 0.0
        dx, dy, dz = apx - v * abx, apy - v * aby, apz - v * abz
        return dx * dx + dy * dy + dz * dz

    cpx, cpy, cpz = p[0] - c[0], p[1] - c[1], p[2] - c[2]
    d5 = abx * cpx + aby * cpy + abz * cpz
    d6 = acx * cpx + acy * cpy + acz * cpz
    if d6 >= 0.0 and d5 <= d6:
        return cpx * cpx + cpy * cpy + cpz * cpz

    vb = d5 * d2 - d1 * d6
    if vb <= 0.0 and d2 >= 0.0 and d6 <= 0.0:
        denom = d2 - d6
        w = d2 / denom if denom != 0.0 else 0.0
        dx, dy, dz = apx - w * acx, apy - w * acy, apz - w * acz
        return dx * dx + dy * dy + dz * dz

    va = d3 * d6 - d5 * d4
    if va <= 0.0 and (d4 - d3) >= 0.0 and (d5 - d6) >= 0.0:
        denom = (d4 - d3) + (d5 - d6)
        w = (d4 - d3) / denom if denom != 0.0 else 0.0
        dx = p[0] - (b[0] + w * (c[0] - b[0]))
        dy = p[1] - (b[1] + w * (c[1] - b[1]))
        dz = p[2] - (b[2] + w * (c[2] - b[2]))
        return dx * dx + dy * dy + dz * dz

    denom = va + vb + vc
    if denom == 0.0:  # degenerate triangle — fall back to vertex a
        return apx * apx + apy * apy + apz * apz
    v = vb / denom
    w = vc / denom
    dx = apx - (v * abx + w * acx)
    dy = apy - (v * aby + w * acy)
    dz = apz - (v * abz + w * acz)
    return dx * dx + dy * dy + dz * dz


def _mesh_area(tris) -> float:
    """Total area of a list of (a, b, c) vertex triples."""
    total = 0.0
    for a, b, c in tris:
        ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
        vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
        nx = uy * vz - uz * vy
        ny = uz * vx - ux * vz
        nz = ux * vy - uy * vx
        total += 0.5 * math.sqrt(nx * nx + ny * ny + nz * nz)
    return total


class TriangleGrid:
    """Uniform spatial grid over a triangle mesh for nearest-surface queries.

    Each triangle is registered in every cell its bounding box touches.
    A query walks outward in cubic shells around the query point's cell and
    stops once the best distance found is closer than any unvisited shell
    could possibly be.
    """

    def __init__(self, vertices, triangles, target_per_cell: float = 3.0):
        self.tris = [
            (vertices[i], vertices[j], vertices[k]) for i, j, k in triangles
        ]
        xs = [v[0] for v in vertices]
        ys = [v[1] for v in vertices]
        zs = [v[2] for v in vertices]
        if not xs:
            self.cells = {}
            self.cell = 1.0
            self.dims = (1, 1, 1)
            self.origin = (0.0, 0.0, 0.0)
            return
        pad = 1e-6
        self.origin = (min(xs) - pad, min(ys) - pad, min(zs) - pad)
        span = (
            max(xs) - min(xs) + 2 * pad,
            max(ys) - min(ys) + 2 * pad,
            max(zs) - min(zs) + 2 * pad,
        )
        # Size the cell from surface area, not bounding-box volume: the
        # triangles form a 2D sheet inside the box, and a flat part has no
        # volume to divide by at all. Occupied cells go as area / cell², so
        # cell = sqrt(target_per_cell * area / triangle count) puts roughly
        # target_per_cell triangles in each.
        area = _mesh_area(self.tris)
        count = max(len(self.tris), 1)
        if area > 0.0:
            self.cell = math.sqrt(target_per_cell * area / count)
        else:
            self.cell = max(span) / 8.0
        # Never so fine that one triangle spans a huge number of cells.
        self.cell = max(self.cell, max(span) / 512.0, 1e-9)
        self.dims = tuple(max(int(s / self.cell) + 1, 1) for s in span)
        self.max_ring = max(self.dims)

        cells = {}
        ox, oy, oz = self.origin
        c = self.cell
        for idx, (a, b, cc) in enumerate(self.tris):
            i0 = int((min(a[0], b[0], cc[0]) - ox) / c)
            i1 = int((max(a[0], b[0], cc[0]) - ox) / c)
            j0 = int((min(a[1], b[1], cc[1]) - oy) / c)
            j1 = int((max(a[1], b[1], cc[1]) - oy) / c)
            k0 = int((min(a[2], b[2], cc[2]) - oz) / c)
            k1 = int((max(a[2], b[2], cc[2]) - oz) / c)
            for i in range(i0, i1 + 1):
                for j in range(j0, j1 + 1):
                    for k in range(k0, k1 + 1):
                        cells.setdefault((i, j, k), []).append(idx)
        self.cells = cells

    def nearest_distance(self, p) -> float:
        """Distance from p to the closest point on the mesh surface."""
        if not self.tris:
            return float("inf")
        c = self.cell
        ox, oy, oz = self.origin
        ci = int((p[0] - ox) / c)
        cj = int((p[1] - oy) / c)
        ck = int((p[2] - oz) / c)
        inside = (
            0 <= ci < self.dims[0]
            and 0 <= cj < self.dims[1]
            and 0 <= ck < self.dims[2]
        )
        if not inside:
            # Outside the mesh's grid: the shell bound below assumes p sits
            # in its own cell, so fall back to an exhaustive scan. Only
            # happens for points well clear of the reference surface.
            best2 = float("inf")
            for tri in self.tris:
                d2 = _point_triangle_distance2(p, tri[0], tri[1], tri[2])
                if d2 < best2:
                    best2 = d2
            return math.sqrt(best2)

        best2 = float("inf")
        checked = set()
        cells = self.cells
        tris = self.tris
        ring = 0
        while ring <= self.max_ring:
            for i in range(ci - ring, ci + ring + 1):
                for j in range(cj - ring, cj + ring + 1):
                    for k in range(ck - ring, ck + ring + 1):
                        # only the shell surface, inner cells already done
                        if ring and (
                            abs(i - ci) != ring
                            and abs(j - cj) != ring
                            and abs(k - ck) != ring
                        ):
                            continue
                        for idx in cells.get((i, j, k), ()):
                            if idx in checked:
                                continue
                            checked.add(idx)
                            tri = tris[idx]
                            d2 = _point_triangle_distance2(
                                p, tri[0], tri[1], tri[2]
                            )
                            if d2 < best2:
                                best2 = d2
            # A triangle first appearing at shell ring+1 is at least
            # ring*cell away from p, so this bound is safe.
            if best2 <= (ring * c) ** 2:
                break
            ring += 1
        return math.sqrt(best2)


def _radical_inverse(n: int, base: int) -> float:
    """Van der Corput radical inverse — a deterministic low-discrepancy value."""
    result = 0.0
    inv = 1.0 / base
    f = inv
    while n > 0:
        result += (n % base) * f
        n //= base
        f *= inv
    return result


def sample_mesh_points(vertices, triangles, count: int) -> list:
    """Sample ``count`` points spread over the mesh surface, area-weighted.

    Deterministic: triangles are picked by stratifying the cumulative-area
    axis and barycentric coordinates come from a Halton sequence, so no
    random number generator is involved and results are reproducible across
    machines and Python versions.
    """
    if not triangles or count <= 0:
        return []
    cumulative = []
    total = 0.0
    for i, j, k in triangles:
        a, b, c = vertices[i], vertices[j], vertices[k]
        ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
        vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
        nx = uy * vz - uz * vy
        ny = uz * vx - ux * vz
        nz = ux * vy - uy * vx
        total += 0.5 * math.sqrt(nx * nx + ny * ny + nz * nz)
        cumulative.append(total)
    if total <= 0.0:
        return []

    points = []
    for n in range(count):
        target = (n + 0.5) / count * total
        t_idx = min(bisect.bisect_left(cumulative, target), len(triangles) - 1)
        i, j, k = triangles[t_idx]
        a, b, c = vertices[i], vertices[j], vertices[k]
        r1 = _radical_inverse(n + 1, 2)
        r2 = _radical_inverse(n + 1, 3)
        s = math.sqrt(r1)
        w0 = 1.0 - s
        w1 = s * (1.0 - r2)
        w2 = s * r2
        points.append((
            a[0] * w0 + b[0] * w1 + c[0] * w2,
            a[1] * w0 + b[1] * w1 + c[1] * w2,
            a[2] * w0 + b[2] * w1 + c[2] * w2,
        ))
    return points


def _distance_stats(distances: list) -> dict:
    """max / mean / rms / 95th percentile of a distance list."""
    if not distances:
        return {"max": 0.0, "mean": 0.0, "rms": 0.0, "p95": 0.0}
    n = len(distances)
    ordered = sorted(distances)
    return {
        "max": ordered[-1],
        "mean": sum(ordered) / n,
        "rms": math.sqrt(sum(d * d for d in ordered) / n),
        "p95": ordered[min(int(0.95 * n), n - 1)],
    }


def hausdorff_distance(mesh_a, mesh_b, samples: int = 2000) -> dict:
    """Two-sided approximate Hausdorff distance between two meshes.

    Args:
        mesh_a: (vertices, triangles) of the reference mesh.
        mesh_b: (vertices, triangles) of the mesh being compared.
        samples: points sampled per direction; must be positive.

    Returns a dict with ``forward`` (A→B), ``backward`` (B→A) and combined
    ``hausdorff`` / ``mean`` / ``rms`` / ``p95`` values, all in model units.
    """
    if samples < 1:
        # Zero samples would report a flawless match for any pair of shapes.
        raise ValueError(f"samples must be at least 1, got {samples}")

    va, ta = mesh_a
    vb, tb = mesh_b
    grid_a = TriangleGrid(va, ta)
    grid_b = TriangleGrid(vb, tb)

    pts_a = sample_mesh_points(va, ta, samples)
    pts_b = sample_mesh_points(vb, tb, samples)
    fwd = [grid_b.nearest_distance(p) for p in pts_a]
    bwd = [grid_a.nearest_distance(p) for p in pts_b]

    f_stats = _distance_stats(fwd)
    b_stats = _distance_stats(bwd)
    both = _distance_stats(fwd + bwd)
    return {
        "samples": samples,
        "forward": f_stats,
        "backward": b_stats,
        "hausdorff": max(f_stats["max"], b_stats["max"]),
        "mean": both["mean"],
        "rms": both["rms"],
        "p95": both["p95"],
    }


def _triangulate(shape, deflection, angular_deflection, remesh):
    """Return (vertices, triangles) for a shape, meshing it first if asked.

    Meshing writes a triangulation into the shape, so a copy is meshed and
    the caller's shape is left exactly as it was — generated tests must not
    mutate the fixture they are handed.
    """
    from OCP.BRep import BRep_Tool
    from OCP.BRepBuilderAPI import BRepBuilderAPI_Copy
    from OCP.BRepMesh import BRepMesh_IncrementalMesh
    from OCP.BRepTools import BRepTools
    from OCP.TopLoc import TopLoc_Location

    target = shape.wrapped
    if remesh:
        target = BRepBuilderAPI_Copy(target).Shape()
        BRepTools.Clean_s(target)
        BRepMesh_IncrementalMesh(
            target, deflection, False, angular_deflection, True
        )

    vertices: list = []
    triangles: list = []
    explorer = TopExp_Explorer(target, TopAbs_FACE)
    while explorer.More():
        face = TopoDS.Face_s(explorer.Current())
        loc = TopLoc_Location()
        tri = BRep_Tool.Triangulation_s(face, loc)
        if tri is None:
            explorer.Next()
            continue
        transform = loc.Transformation()
        flipped = face.Orientation() == TopAbs_REVERSED
        offset = len(vertices)
        for i in range(1, tri.NbNodes() + 1):
            pnt = tri.Node(i).Transformed(transform)
            vertices.append((pnt.X(), pnt.Y(), pnt.Z()))
        for i in range(1, tri.NbTriangles() + 1):
            n1, n2, n3 = tri.Triangle(i).Get()
            if flipped:
                n2, n3 = n3, n2
            triangles.append((offset + n1 - 1, offset + n2 - 1, offset + n3 - 1))
        explorer.Next()
    return vertices, triangles


_HAUSDORFF_CACHE = {}


def _shape_signature(shape):
    """Cheap key identifying a shape's geometry (not its object identity).

    Volume and envelope alone would collide on exactly the differences
    this test exists to catch — a mirrored part, or a feature moved
    within the same envelope — so the centre of mass and surface area
    go in too.
    """
    volume = GProp_GProps()
    BRepGProp.VolumeProperties_s(shape.wrapped, volume)
    surface = GProp_GProps()
    BRepGProp.SurfaceProperties_s(shape.wrapped, surface)
    com = volume.CentreOfMass()
    bb = shape.bounding_box()
    return (
        round(volume.Mass(), 9), round(surface.Mass(), 9),
        round(com.X(), 9), round(com.Y(), 9), round(com.Z(), 9),
        round(bb.min.X, 9), round(bb.min.Y, 9), round(bb.min.Z, 9),
        round(bb.max.X, 9), round(bb.max.Y, 9), round(bb.max.Z, 9),
    )


def _hausdorff_vs_reference(shape):
    """Two-sided surface deviation between `shape` and the reference mesh.

    Keyed on the shape's geometry rather than on `id()`, because a
    function-scoped pytest fixture hands each test a freshly built part —
    the max and mean tests would otherwise pay for the whole measurement
    twice.
    """
    key = _shape_signature(shape)
    if key in _HAUSDORFF_CACHE:
        return _HAUSDORFF_CACHE[key]
    reference = decode_mesh(REF_MESH)
    deflection = REF_MESH["deflection"]
    angular = REF_MESH["angular_deflection"]
    actual = _triangulate(shape, deflection, angular, True)
    # The reference mesh was capped; cap this one too, or a part with far
    # more detail makes these pure-Python distance queries crawl.
    attempts = 0
    while len(actual[1]) > REF_MESH["max_triangles"] and attempts < 6:
        deflection *= 1.7
        angular = min(angular * 1.3, 1.0)
        attempts += 1
        actual = _triangulate(shape, deflection, angular, True)
    result = hausdorff_distance(reference, actual, HAUSDORFF_SAMPLES)
    # Coarsening costs accuracy, so the floor has to move with it. Chord
    # error scales with the deflection the mesh was built at, which is
    # all this needs: reading it off the candidate's own facets would let
    # the part under test widen the tolerance it is judged by.
    candidate_error = REF_MESH["candidate_resolution"] * (
        deflection / REF_MESH["deflection"]
    )
    result["floor"] = 2.0 * (REF_MESH["resolution"] + candidate_error)
    result["deflection"] = deflection
    if len(_HAUSDORFF_CACHE) > 4:
        _HAUSDORFF_CACHE.clear()
    _HAUSDORFF_CACHE[key] = result
    return result


# ═══════════════════════════════════════════════════════════
# Tests for Holder
# ═══════════════════════════════════════════════════════════

class TestGlobalProperties:
    """Volume, surface area, bounding box, center of mass."""

    def test_volume(self, part_under_test):
        vol_props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, vol_props)
        vol = vol_props.Mass()
        pct = abs(vol - REF_VOLUME) / REF_VOLUME * 100
        direction = 'larger' if vol > REF_VOLUME else 'smaller'
        assert pct / 100 < 0.01, (
            f"Volume {vol:.4f} is {direction} than ref {REF_VOLUME} by {abs(vol - REF_VOLUME):.2f} mm³ ({pct:.1f}%) — adjust overall dimensions"
        )

    def test_surface_area(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.SurfaceProperties_s(part_under_test.wrapped, props)
        area = props.Mass()
        pct = abs(area - REF_SURFACE_AREA) / REF_SURFACE_AREA * 100
        direction = 'larger' if area > REF_SURFACE_AREA else 'smaller'
        assert pct / 100 < 0.02, (
            f"Surface area {area:.4f} is {direction} than ref {REF_SURFACE_AREA} ({pct:.1f}% off) — check feature dimensions"
        )

    def test_bounding_box(self, part_under_test):
        bb = part_under_test.bounding_box()
        tol = 0.1
        assert abs(bb.min.X - REF_BBOX_MIN[0]) < tol, "BBox min X mismatch"
        assert abs(bb.max.X - REF_BBOX_MAX[0]) < tol, "BBox max X mismatch"
        assert abs(bb.min.Y - REF_BBOX_MIN[1]) < tol, "BBox min Y mismatch"
        assert abs(bb.max.Y - REF_BBOX_MAX[1]) < tol, "BBox max Y mismatch"
        assert abs(bb.min.Z - REF_BBOX_MIN[2]) < tol, "BBox min Z mismatch"
        assert abs(bb.max.Z - REF_BBOX_MAX[2]) < tol, "BBox max Z mismatch"

    def test_center_of_mass(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, props)
        com = props.CentreOfMass()
        for i, (actual, ref) in enumerate(zip(
            (com.X(), com.Y(), com.Z()), REF_CENTER_OF_MASS)):
            assert abs(actual - ref) < 0.2, (
                f"CoM axis {i}: {actual:.4f} vs ref {ref:.4f}"
            )


class TestMomentsOfInertia:
    """Inertia tensor — very sensitive to mass distribution."""

    def test_principal_moments(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, props)
        mat = props.MatrixOfInertia()
        for key, (r, c) in [("Ixx", (1,1)), ("Iyy", (2,2)), ("Izz", (3,3))]:
            actual = mat.Value(r, c)
            ref = REF_INERTIA[key]
            if abs(ref) > 1e-6:
                pct = abs(actual - ref) / abs(ref) * 100
                assert pct / 100 < 0.02, (
                    f"{key}: {actual:.4f} vs ref {ref:.4f} ({pct:.1f}% off) — mass distribution differs"
                )

    def test_off_diagonal_moments(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, props)
        mat = props.MatrixOfInertia()
        for key, (r, c) in [("Ixy", (1,2)), ("Ixz", (1,3)), ("Iyz", (2,3))]:
            actual = mat.Value(r, c)
            ref = REF_INERTIA[key]
            tol = max(abs(ref) * 0.02, 1.0)
            assert abs(actual - ref) < tol, (
                f"{key}: {actual:.4f} vs ref {ref:.4f} — part may be rotated or asymmetric"
            )


class TestCrossSections:
    """Cross-sectional area and centroid at 24 positions along Z."""

    _plane_maker = staticmethod(lambda v: gp_Pln(gp_Pnt(0, 0, v), gp_Dir(0, 0, 1)))
    _uv_axes = ("X", "Y")

    @pytest.mark.parametrize("ref", REF_CROSS_SECTIONS,
        ids=[f"Z={cs['position']}" for cs in REF_CROSS_SECTIONS])
    def test_cross_section_area(self, part_under_test, ref):
        props = _cross_section_props(part_under_test, ref["position"], self._plane_maker, self._uv_axes)
        area = props["area"]
        ref_area = ref["area"]
        if ref_area < 0.01:  # near-zero slice
            assert area < 0.5, f"Expected ~0 area at pos={ref['position']}, got {area:.4f}"
        else:
            pct = abs(area - ref_area) / ref_area * 100
            direction = 'too large' if area > ref_area else 'too small'
            assert pct / 100 < 0.03, (
                f"Area at Z={ref['position']}: {area:.4f} vs ref {ref_area:.4f} "
                f"({pct:.1f}% {direction}) — adjust radius/fillet at this position"
            )

    @pytest.mark.parametrize("ref", REF_CROSS_SECTIONS,
        ids=[f"Z={cs['position']}" for cs in REF_CROSS_SECTIONS])
    def test_cross_section_centroid(self, part_under_test, ref):
        ref_area = ref["area"]
        if ref_area < 0.01:
            pytest.skip("near-zero area — centroid meaningless")
        props = _cross_section_props(part_under_test, ref["position"], self._plane_maker, self._uv_axes)
        for ref_key, prop_key in [("centroid_x", "centroid_u"), ("centroid_y", "centroid_v")]:
            actual = props[prop_key]
            ref_val = ref[ref_key]
            diff = actual - ref_val
            assert abs(diff) < 0.2, (
                f"Centroid {ref_key} at Z={ref['position']}: {actual:.4f} vs ref {ref_val:.4f} "
                f"(shifted {'positive' if diff > 0 else 'negative'} by {abs(diff):.3f}mm) — check alignment"
            )

    @pytest.mark.parametrize("ref", REF_CROSS_SECTIONS,
        ids=[f"Z={cs['position']}" for cs in REF_CROSS_SECTIONS])
    def test_cross_section_shape(self, part_under_test, ref):
        """2D moments capture cross-section shape, not just area."""
        ref_area = ref["area"]
        if ref_area < 0.01:
            pytest.skip("near-zero area — shape moments meaningless")
        props = _cross_section_props(part_under_test, ref["position"], self._plane_maker, self._uv_axes)
        for ref_key, prop_key in [("Ixx_2d", "Iuu_2d"), ("Iyy_2d", "Ivv_2d")]:
            ref_val = ref.get(ref_key, 0.0)
            if abs(ref_val) < 0.01:
                continue
            actual = props[prop_key]
            pct = abs(actual - ref_val) / abs(ref_val) * 100
            assert pct / 100 < 0.05, (
                f"Shape moment {ref_key} at Z={ref['position']}: {actual:.4f} vs ref {ref_val:.4f} "
                f"({pct:.1f}% off) — cross-section shape differs"
            )


class TestRadialProfile:
    """Radial distance from axis at 15 positions × 12 angles."""

    @pytest.mark.parametrize("ref", REF_RADIAL_PROFILE,
        ids=[f"Z={rp['position']}" for rp in REF_RADIAL_PROFILE])
    def test_radial_profile(self, part_under_test, ref):
        pos = ref["position"]
        for deg_str, ref_r in ref["radii"].items():
            deg = float(deg_str)
            if ref_r is None:
                continue
            origin = gp_Pnt(0, 0, pos)
            direction = gp_Dir(math.cos(math.radians(deg)), math.sin(math.radians(deg)), 0)
            actual_r = _radial_distance(part_under_test, origin, direction)
            assert actual_r is not None, (
                f"No intersection at Z={pos}, angle={deg}°"
            )
            hint = 'excess' if actual_r > ref_r else 'missing'
            assert abs(actual_r - ref_r) < 0.15, (
                f"Radial at Z={pos} angle={deg}°: {actual_r:.4f} vs ref {ref_r:.4f} — {hint} material"
            )


class TestSurfaceDeviation:
    """Hausdorff distance — worst-case point-to-surface deviation.

    Volume, area and cross-sections are aggregates: they can all agree
    while the surface is locally wrong. These tests sample points on both
    surfaces and measure how far each one is from the other surface.
    """

    def test_max_deviation(self, part_under_test):
        """No sampled point on either surface is further than the tolerance.

        This is a sampled estimate, not a proof: with HAUSDORFF_SAMPLES
        points per direction against 2696
        reference triangles, a defect confined to a few triangles can be
        missed. Raise --hausdorff-samples to sample the surface harder.
        """
        result = _hausdorff_vs_reference(part_under_test)
        tolerance = max(0.3, result["floor"])
        fwd = result["forward"]["max"]
        bwd = result["backward"]["max"]
        side = "missing material" if fwd > bwd else "excess material"
        assert result["hausdorff"] < tolerance, (
            f"Hausdorff distance {result['hausdorff']:.4f}mm exceeds "
            f"{tolerance:.4f}mm over {result['samples']} "
            f"samples/direction (ref→part {fwd:.4f}, part→ref "
            f"{bwd:.4f}, 95th pct {result['p95']:.4f}) — worst area "
            f"looks like {side}"
        )

    def test_mean_deviation(self, part_under_test):
        """The surfaces agree closely on average, not just at worst case."""
        result = _hausdorff_vs_reference(part_under_test)
        tolerance = max(0.05, result["floor"] / 4.0)
        assert result["mean"] < tolerance, (
            f"Mean surface deviation {result['mean']:.4f}mm exceeds "
            f"{tolerance:.4f}mm (RMS {result['rms']:.4f}, 95th pct "
            f"{result['p95']:.4f}) — the whole surface is off, not just "
            f"a local feature"
        )


class TestBuildQuality:
    """Solid validity, watertight check, single body."""

    def test_single_solid(self, part_under_test):
        """Result must be a single solid (not split by failed booleans)."""
        from OCP.TopAbs import TopAbs_SOLID
        exp = TopExp_Explorer(part_under_test.wrapped, TopAbs_SOLID)
        count = 0
        while exp.More():
            count += 1
            exp.Next()
        assert count == 1, (
            f"Expected 1 solid(s), got {count}"
        )

    def test_no_free_edges(self, part_under_test):
        """No free edges — the solid must be watertight."""
        from OCP.ShapeAnalysis import ShapeAnalysis_FreeBounds
        fb = ShapeAnalysis_FreeBounds(part_under_test.wrapped)
        open_wires = fb.GetOpenWires()
        exp = TopExp_Explorer(open_wires, TopAbs_EDGE)
        free_count = 0
        while exp.More():
            free_count += 1
            exp.Next()
        assert free_count == 0, (
            f"Found {free_count} free edge(s) — solid is not watertight"
        )

    def test_shape_valid(self, part_under_test):
        """OCCT validity check — no degenerate or corrupt geometry."""
        from OCP.BRepCheck import BRepCheck_Analyzer
        analyzer = BRepCheck_Analyzer(part_under_test.wrapped)
        assert analyzer.IsValid(), "BRepCheck_Analyzer reports invalid geometry"
